Added regression tests into workflow

diff --git a/.github/workflows/regression_test.yml b/.github/workflows/regression_test.yml
--- a/.github/workflows/regression_test.yml
+++ b/.github/workflows/regression_test.yml
@@ -1,15 +1,13 @@
-name: System Test
+name: Regression Tests
 
-on:
-  workflow_run:
-    workflows: [ CI ]
-    types: 
-        - completed
+on: 
+  push:
+    branches: [ "fix/devremoval" ]
 
   workflow_dispatch:
 
 jobs:
-  system_test:
+  regression_test:
     runs-on: ubuntu-latest
     container: mcr.microsoft.com/playwright:v1.50.1-jammy
     steps:
@@ -38,21 +36,21 @@ jobs:
       - name: Set HOME environment variable
         run: echo "HOME=/root" >> $GITHUB_ENV
 
-      - name: Run System Tests
-        run: xvfb-run npx playwright test tests/playwright/systemTests --headed --workers=1
+      - name: Run Regression Tests
+        run: npm run test:regression
 
-      - name: Report System Test Status in PR
-        uses: actions/github-script@v7
-        with:
-          script: |
-            github.rest.checks.create({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              name: "System Tests",
-              head_sha: "${{ github.event.workflow_run.head_sha }}",
-              status: "completed",
-              conclusion: "success"
-            })
+     # - name: Report Smoke Test Status in PR
+     #   uses: actions/github-script@v7
+     #   with:
+     #     script: |
+     #       github.rest.checks.create({
+     #         owner: context.repo.owner,
+     #         repo: context.repo.repo,
+     #         name: "System Tests",
+     #         head_sha: "${{ github.event.workflow_run.head_sha }}",
+     #         status: "completed",
+     #         conclusion: "success"
+     #       })
               
       - uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
@@ -61,12 +59,10 @@ jobs:
           path: playwright-report/
           retention-days: 30
 
-  smoke-failure:
-     runs-on: ubuntu-latest
-     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
-     steps:
-        - run: |
-            echo 'The smoke test workflow failed'
-            exit 1
-
-
+ # system-failure:
+ #    runs-on: ubuntu-latest
+ #    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+ #    steps:
+ #       - run: |
+ #           echo 'The system test workflow failed'
+ #           exit 1
