Added conditionals on regression test to only run on system test success and only on push instead of pr

diff --git a/.github/workflows/regression_test.yml b/.github/workflows/regression_test.yml
--- a/.github/workflows/regression_test.yml
+++ b/.github/workflows/regression_test.yml
@@ -1,8 +1,10 @@
 name: Regression Tests
 
-on: 
-  push:
-    branches: [ "fix/devremoval" ]
+on:
+  workflow_run:
+    workflows: [ "System Test" ]
+    types: 
+    - completed
 
   workflow_dispatch:
 
@@ -10,6 +12,7 @@ jobs:
   regression_test:
     runs-on: ubuntu-latest
     container: mcr.microsoft.com/playwright:v1.50.1-jammy
+    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_repository.full_name == github.repository}}
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
@@ -39,18 +42,18 @@ jobs:
       - name: Run Regression Tests
         run: npm run test:regression
 
-     # - name: Report Smoke Test Status in PR
-     #   uses: actions/github-script@v7
-     #   with:
-     #     script: |
-     #       github.rest.checks.create({
-     #         owner: context.repo.owner,
-     #         repo: context.repo.repo,
-     #         name: "System Tests",
-     #         head_sha: "${{ github.event.workflow_run.head_sha }}",
-     #         status: "completed",
-     #         conclusion: "success"
-     #       })
+      - name: Report Regression Test Status in PR
+        uses: actions/github-script@v7
+        with:
+          script: |
+            github.rest.checks.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              name: "Regression Tests",
+              head_sha: "${{ github.event.workflow_run.head_sha }}",
+              status: "completed",
+              conclusion: "success"
+            })
               
       - uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
@@ -59,10 +62,10 @@ jobs:
           path: playwright-report/
           retention-days: 30
 
- # system-failure:
- #    runs-on: ubuntu-latest
- #    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
- #    steps:
- #       - run: |
- #           echo 'The system test workflow failed'
- #           exit 1
+  system-failure:
+     runs-on: ubuntu-latest
+     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+     steps:
+        - run: |
+            echo 'The system test workflow failed'
+            exit 1
